let state = {
	form: [
		{ link: '../img/form.png', value: '../img/form.png' },
		{ link: '../img/form2.png', value: '../img/form2.png' },
		{ link: '../img/form3.png', value: '../img/form3.png' },
		{ link: '../img/form4.png', value: '../img/form4.png' },
		{ link: '../img/form5.png', value: '../img/form5.png' },
		{ link: '../img/form6.png', value: '../img/form6.png' },
		{ link: '../img/form7.png', value: '../img/form7.png' },
		{ link: '../img/form8.png', value: '../img/form8.png' },
		{ link: '../img/form9.png', value: '../img/form9.png' },
		{ link: '../img/form10.png', value: '../img/form10.png' },
		{ link: '../img/form11.png', value: '../img/form11.png' },
		{ link: '../img/form1.png', value: '../img/form1.png' },
	],
	logo: [
		{ link: '../img/Club1.png', value: '../img/Club1.png' },
		{ link: '../img/Club2.png', value: '../img/Club2.png' },
		{ link: '../img/Club3.png', value: '../img/Club3.png' },
		{ link: '../img/Club4.png', value: '../img/Club4.png' },
		{ link: '../img/Club5.png', value: '../img/Club5.png' },
		{ link: '../img/Club6.png', value: '../img/Club6.png' },
		{ link: '../img/Club7.png', value: '../img/Club7.png' },
		{ link: '../img/Club8.png', value: '../img/Club8.png' },
	],
	nav: [
		{ link: '/', text: 'Home' },
		{ link: '/game', text: 'Game' },
		{ link: '/transfer', text: 'Transfer' },
		{ link: '/composition', text: 'Сomposition' },
		{ link: '/buy', text: 'Buy' },
		{ link: '/creatingteam', text: 'Create a team' },
		{ link: '/registration', text: 'Registration' },
	],
}

export default state
// "teams": [
// 	{
// 		"id": 1,
// 		"clubName": "Liverpool",
// 		"force": 1790,
// 		"logotype": "/img/Liverpool.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 2,
// 		"clubName": "Manchester United",
// 		"force": 1690,
// 		"logotype": "/img/ManchesterUnited.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 3,
// 		"clubName": "Manchester City",
// 		"force": 1800,
// 		"logotype": "/img/ManchesterCity.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"form": 1
// 	},
// 	{
// 		"id": 4,
// 		"clubName": "Chelsea",
// 		"force": 1690,
// 		"logotype": "/img/Chelsea.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"form": 1
// 	},
// 	{
// 		"id": 5,
// 		"clubName": "Valencia",
// 		"force": 1590,
// 		"logotype": "/img/Valencia.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 6,
// 		"clubName": "Arsenal",
// 		"force": 1660,
// 		"logotype": "/img/Arsenal.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 7,
// 		"clubName": "Everton",
// 		"force": 1540,
// 		"logotype": "/img/Everton.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 8,
// 		"clubName": "Crystal Pelas",
// 		"force": 1450,
// 		"logotype": "/img/CrystalPelas.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 9,
// 		"clubName": "Blackburn Rovers",
// 		"force": 1370,
// 		"logotype": "/img/BlackburnRovers.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 10,
// 		"clubName": "Aston Villa",
// 		"force": 1500,
// 		"logotype": "/img/AstonVilla.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 11,
// 		"clubName": "Bavaria",
// 		"force": 1690,
// 		"logotype": "/img/Bavaria.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 12,
// 		"clubName": "Koln",
// 		"force": 1460,
// 		"logotype": "/img/Koln.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 13,
// 		"clubName": "Real Madrid",
// 		"force": 1800,
// 		"logotype": "/img/RealMadrid.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 14,
// 		"clubName": "Barcelona",
// 		"force": 1750,
// 		"logotype": "/img/Barcelona.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 15,
// 		"clubName": "Bayer Leverkusen",
// 		"force": 1650,
// 		"logotype": "/img/BayerLeverkusen.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 1,
// 		"city": "",
// 		"uniform": 1
// 	},
// 	{
// 		"id": 16,
// 		"clubName": "PSG",
// 		"force": 1600,
// 		"logotype": "../img/Club3.png",
// 		"game": 0,
// 		"victory": 0,
// 		"draw": 0,
// 		"defeat": 0,
// 		"glasses": 0,
// 		"money": 0,
// 		"numberofplayers": 0,
// 		"difficulty": 40000000,
// 		"city": "Paris",
// 		"uniform": "../img/form2.png"
// 	}
// ],
